name: Merge master to develop
on:
  push:
    branches:
      - 'master'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Merge master -> develop
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          target_branch: develop
          github_token: ${{ github.token }}
